steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/personal-website-449800/cloud-run-source-deploy/personal-website/website:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/personal-website-449800/cloud-run-source-deploy/personal-website/website:$COMMIT_SHA']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'website'
    - '--image'
    - 'us-central1-docker.pkg.dev/personal-website-449800/cloud-run-source-deploy/personal-website/website:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY